language: python

sudo: required

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py35-django19-drf33
    - TOX_ENV=py35-django18-drf33
    - TOX_ENV=py35-django18-drf32
    - TOX_ENV=py35-django18-drf31
    - TOX_ENV=py35-django18-drf30
    - TOX_ENV=py34-django19-drf33
    - TOX_ENV=py34-django18-drf33
    - TOX_ENV=py34-django18-drf32
    - TOX_ENV=py34-django18-drf31
    - TOX_ENV=py34-django18-drf30
    - TOX_ENV=py34-django17-drf33
    - TOX_ENV=py34-django17-drf32
    - TOX_ENV=py34-django17-drf31
    - TOX_ENV=py34-django17-drf30
    - TOX_ENV=py34-django17-drf24
    - TOX_ENV=py33-django18-drf33
    - TOX_ENV=py33-django18-drf32
    - TOX_ENV=py33-django18-drf31
    - TOX_ENV=py33-django18-drf30
    - TOX_ENV=py33-django17-drf33
    - TOX_ENV=py33-django17-drf32
    - TOX_ENV=py33-django17-drf31
    - TOX_ENV=py33-django17-drf30
    - TOX_ENV=py33-django17-drf24
    - TOX_ENV=py27-django19-drf33
    - TOX_ENV=py27-django18-drf33
    - TOX_ENV=py27-django18-drf32
    - TOX_ENV=py27-django18-drf31
    - TOX_ENV=py27-django18-drf30
    - TOX_ENV=py27-django17-drf33
    - TOX_ENV=py27-django17-drf32
    - TOX_ENV=py27-django17-drf31
    - TOX_ENV=py27-django17-drf30
    - TOX_ENV=py27-django17-drf24

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

before_install:
  - chmod +x install-centrifugo.sh
  - ./install-centrifugo.sh

install:
  # Virtualenv < 14 is required to keep the Python 3.2 builds running.
  - pip install tox

script:
    - tox -e $TOX_ENV

